# This is the default tools.xuggle properties file
# Created 29 May 2011

# Properties used by xuggle
Xuggle.Dialog.NoXuggle.Title=Xuggle not found
Xuggle.Dialog.NoXuggle.Message1=Xuggle (cross-platform video engine) is not installed.
Xuggle.Dialog.NoXuggle.Message2=Download Xuggle from http://www.xuggle.com/xuggler/downloads/.
Xuggle.Action.AboutXuggle=About Xuggle...
Xuggle.Dialog.AboutXuggle.Title=About Xuggle
Xuggle.Dialog.AboutXuggle.Message.Version=Xuggle version
Xuggle.Dialog.AboutXuggle.Message.Home=Xuggle home:
Xuggle.Dialog.AboutXuggle.Message.Path=Xuggle jar path:
Xuggle.Dialog.NoVideoEngine.Message1=By default Tracker can open animated gifs, images and image sequences,
Xuggle.Dialog.NoVideoEngine.Message2=but a separate video engine is required to open other video types.
Xuggle.Dialog.NoVideoEngine.Message3=To install Xuggle, the recommended free open source cross-platform
Xuggle.Dialog.NoVideoEngine.Message4=video engine, download the latest Tracker installer from
Xuggle.Dialog.NoVideoEngine.Title=No Video Engine
Xuggle.Dialog.NoXuggle.Message1=Xuggle is not installed or not working (reason unknown).
Xuggle.Dialog.NoXuggle.Message2=To install Xuggle, download the latest Tracker installer from
Xuggle.Dialog.NoXuggle.Title=Xuggle Unavailable