"""
make_video_magnetic.py
======================
Playwright screen recording of the Bar Magnet & Compass simulation,
synchronised to narration_magnetic.mp3 (generated by generate_narration_magnetic.py).

Requirements:
  pip install playwright
  playwright install chromium

Output:
  magnetic_field_video.mp4   (1280 x 720, H.264 + AAC ~6 min)

Layout facts (1280x720 viewport, found by inspection):
  comboBox (magnet presets):   x=13, y=13, w=254, h=54  -> centre (140, 40)
  checkBox  (show Compass):    checkbox at (298, 38); label "show Compass" at (391, 36)
  checkBox2 (show Earth):      checkbox at (528, 38); label "show Earth" at (602, 36)
  resetButton:                 x=687, y=13, w=110, h=54  -> centre (742, 40)
  SVG simulation panel:        x=12.8, y=66.75, w=1254, h=648

Coordinate conversion (simulation -> pixels):
  px = 12.8  + 1254 * (sim_x + 1.5) / 3.0
  py = 66.75 + 648  * (1.0 - sim_y) / 2.0
  (x-range: -1.5 to 1.5;  y-range: -1.0 to 1.0, positive=up)
"""

import os, sys, asyncio, math, json
from pathlib import Path
from playwright.async_api import async_playwright

DIR      = Path(__file__).parent.resolve()
SIM_URL  = (DIR / "index.html").as_uri()
NARR_MP3 = DIR / "narration_magnetic.mp3"
OUT_MP4  = DIR / "magnetic_field_video.mp4"
W, H     = 1280, 720

# Section durations from Kokoro synthesis output
SEC_DUR = {
    "01_intro":                 23.5,
    "02_field_vectors":         33.2,
    "03_rotate_magnet_presets": 36.6,
    "04_drag_and_rotate":       41.4,
    "05_compass_probe":         46.0,
    "06_oscillation":           44.2,
    "07_earth_field":           43.2,
    "08_second_magnet":         44.6,
    "09_conclusion":            34.3,
}

# --- SVG canvas geometry (pixels) ---
SVG_X, SVG_Y = 12.8,  66.75
SVG_W, SVG_H = 1254.0, 648.0
SIM_XMAX, SIM_YMAX = 1.5, 1.0

def s2p(sx, sy):
    """Convert simulation (sx, sy) -> pixel (px, py)."""
    px = int(SVG_X + SVG_W * (sx + SIM_XMAX) / (2 * SIM_XMAX))
    py = int(SVG_Y + SVG_H * (SIM_YMAX - sy) / (2 * SIM_YMAX))
    return px, py

# --- Known control centres ---
CB_MAGNET_CX, CB_MAGNET_CY = 140, 40      # comboBox  (magnet presets)
CHK_COMPASS_X, CHK_COMPASS_Y = 298, 38    # checkBox  (show Compass)
CHK_EARTH_X,   CHK_EARTH_Y   = 528, 38    # checkBox2 (show Earth)
RESET_CX, RESET_CY = 742, 40              # resetButton

# ---------------------------------------------------------------------------
# JS injected once on page load
# ---------------------------------------------------------------------------
INIT_JS = r"""
(function() {
  if (window.__magHelperLoaded) return;
  window.__magHelperLoaded = true;

  // ---- animated fake cursor ----
  var cur = document.createElement('div');
  cur.id = '__cur';
  cur.innerHTML = `<svg width="26" height="34" viewBox="0 0 26 34">
    <path d="M2 2 L2 26 L7 20 L13 32 L17 30 L11 18 L20 18 Z"
          fill="white" stroke="#111" stroke-width="2"/>
  </svg>`;
  cur.style.cssText =
    'position:fixed;z-index:99999;pointer-events:none;top:200px;left:200px;' +
    'transition:top 0.4s ease,left 0.4s ease;';
  document.body.appendChild(cur);

  // ---- caption bar ----
  var cap = document.createElement('div');
  cap.id = '__cap';
  cap.style.cssText =
    'position:fixed;bottom:22px;left:50%;transform:translateX(-50%);' +
    'z-index:99998;background:rgba(0,0,0,0.75);color:#fff;' +
    'font:bold 17px/1.5 Arial,sans-serif;padding:8px 22px;border-radius:9px;' +
    'max-width:900px;text-align:center;pointer-events:none;display:none;';
  document.body.appendChild(cap);

  // ---- highlight ring style ----
  var sty = document.createElement('style');
  sty.textContent =
    '@keyframes __ring{0%{opacity:1;transform:scale(1)}100%{opacity:0;transform:scale(2.6)}}';
  document.head.appendChild(sty);

  // ---- toast (EJSS dialog replacement) ----
  var toast = document.createElement('div');
  toast.id = '__toast';
  toast.style.cssText =
    'position:fixed;top:68px;left:50%;transform:translateX(-50%);z-index:100000;' +
    'background:#1a237e;color:#fff;font:bold 15px Arial,sans-serif;' +
    'padding:10px 24px;border-radius:8px;pointer-events:none;display:none;';
  document.body.appendChild(toast);

  new MutationObserver(function(ms){
    ms.forEach(function(m){
      m.addedNodes.forEach(function(n){
        if(n.nodeType===1&&(n.classList.contains('BoxPanel')||n.classList.contains('EjsBoxPanel'))){
          n.style.display='none';
          toast.textContent='Done!';
          toast.style.display='block';
          setTimeout(function(){toast.style.display='none';},2500);
        }
      });
    });
  }).observe(document.body,{childList:true,subtree:true});

  // ---- Cursor API ----
  window._C = {
    move: function(x,y,ms){
      cur.style.transition='top '+(ms||400)+'ms ease,left '+(ms||400)+'ms ease';
      cur.style.left=x+'px'; cur.style.top=y+'px';
    },
    click: function(){
      var c=cur.cloneNode(true);
      c.style.filter='brightness(2.5)';
      c.style.transition='none';
      c.style.left=cur.style.left; c.style.top=cur.style.top;
      document.body.appendChild(c);
      setTimeout(function(){c.remove();},220);
    },
    ring: function(x,y){
      var r=document.createElement('div');
      r.style.cssText='position:fixed;z-index:99997;pointer-events:none;border:3px solid #FFD700;'+
        'border-radius:50%;width:44px;height:44px;'+
        'left:'+(x-22)+'px;top:'+(y-22)+'px;'+
        'animation:__ring 0.65s ease-out forwards;';
      document.body.appendChild(r);
      setTimeout(function(){r.remove();},700);
    }
  };

  // ---- Caption API ----
  window._caption = function(txt,ms){
    cap.textContent=txt; cap.style.display='block';
    if(ms>0) setTimeout(function(){cap.style.display='none';},ms);
  };
  window._hideCaption = function(){ cap.style.display='none'; };

  // ---- Sim helpers ----
  window._simSet = function(obj){
    if(!window._model) return;
    window._model._readParameters(obj);
    // EJSS animation model methods: try update(), updateView(), then re-init view
    try { window._model.update(); } catch(e) {}
    try { if(window._model._view&&window._model._view.update) window._model._view.update(); } catch(e) {}
  };
  window._simPlay  = function(){ if(window._model&&window._model._play) window._model._play(); };
  window._simPause = function(){ if(window._model&&window._model._pause) window._model._pause(); };
  window._simReset = function(){ if(window._model&&window._model._reset) window._model._reset(); };

  // Helper: set magnet angle (degrees)
  window._setAngle = function(deg){
    var cta = deg*Math.PI/180;
    window._simSet({ca:deg, cta:cta, cs:Math.cos(cta), sc:Math.sin(cta)});
  };

  console.log('__magHelper_ready__');
})();
"""

# ---------------------------------------------------------------------------
async def sleep(s):   await asyncio.sleep(s)

async def move(page, x, y, ms=400):
    await page.evaluate(f"window._C.move({x},{y},{ms})")
    await sleep(ms/1000 + 0.05)

async def ring(page, x, y):
    await page.evaluate(f"window._C.ring({x},{y})")

async def click_pos(page, x, y, ms=350):
    await move(page, x, y, ms)
    await page.evaluate("window._C.click()")
    await ring(page, x, y)
    await sleep(0.15)

async def caption(page, text, show_ms=4500):
    await page.evaluate(f"window._caption({repr(text)}, {show_ms})")

async def hide_cap(page):
    await page.evaluate("window._hideCaption()")

async def sim_set(page, obj):
    await page.evaluate(f"window._simSet({json.dumps(obj)})")
    await sleep(0.25)

async def sim_play(page):
    await page.evaluate("window._simPlay()")
    await sleep(0.2)

async def sim_pause(page):
    await page.evaluate("window._simPause()")
    await sleep(0.2)

async def sim_reset(page):
    await page.evaluate("window._simReset()")
    await sleep(0.4)

async def set_angle(page, deg):
    await page.evaluate(f"window._setAngle({deg})")
    await sleep(0.25)

async def magnet_to(page, sx, sy):
    """Move main magnet to simulation coords (sx, sy)."""
    await sim_set(page, {"xMagnet": sx, "yMagnet": sy,
                         "xMagnetDrag": sx, "yMagnetDrag": sy})

async def compass_to(page, sx, sy):
    """Move compass to simulation coords (sx, sy)."""
    await sim_set(page, {"xCompass": sx, "yCompass": sy,
                         "xCompassstore": sx, "yCompassstore": sy})

async def select_magnet_preset(page, option_text):
    """Select an option in comboBox (magnet presets)."""
    await click_pos(page, CB_MAGNET_CX, CB_MAGNET_CY, 400)
    await page.select_option("#comboBox", label=option_text)
    await sleep(0.5)

async def toggle_compass(page, enable: bool):
    """Set compass checkbox to desired state."""
    cb = page.locator("#checkBox\\.checkbox")
    is_on = await cb.is_checked()
    if is_on != enable:
        await click_pos(page, CHK_COMPASS_X, CHK_COMPASS_Y, 400)
        await cb.click()
        await sleep(0.3)
    # Also set via JS in case checkbox event didn't fire
    await sim_set(page, {"showCompass": enable})

async def toggle_earth(page, enable: bool):
    """Set earth checkbox to desired state."""
    cb = page.locator("#checkBox2\\.checkbox")
    is_on = await cb.is_checked()
    if is_on != enable:
        await click_pos(page, CHK_EARTH_X, CHK_EARTH_Y, 400)
        await cb.click()
        await sleep(0.3)
    await sim_set(page, {"earth": enable})

# ---------------------------------------------------------------------------
# Main recording
# ---------------------------------------------------------------------------
import time as _time

async def record_video():
    async with async_playwright() as pw:
        browser = await pw.chromium.launch(
            headless=True,
            args=["--disable-gpu","--no-sandbox","--disable-dev-shm-usage",
                  "--autoplay-policy=no-user-gesture-required"]
        )
        ctx = await browser.new_context(
            viewport={"width": W, "height": H},
            record_video_dir=str(DIR),
            record_video_size={"width": W, "height": H},
        )
        page = await ctx.new_page()

        print(f"Opening: {SIM_URL}")
        await page.goto(SIM_URL, wait_until="networkidle", timeout=30000)
        await sleep(3)

        await page.evaluate(INIT_JS)
        await sleep(0.5)

        # Start cursor in centre
        await move(page, W//2, H//2, 200)

        # ================================================================
        # 01 INTRO  (23.5 s)
        # ================================================================
        t0 = _time.time()
        await caption(page, "Bar Magnet & Compass — Magnetic Field Explorer")
        # Sweep cursor across top bar to introduce controls
        await move(page, CB_MAGNET_CX, CB_MAGNET_CY, 600)
        await ring(page, CB_MAGNET_CX, CB_MAGNET_CY)
        await sleep(1.5)
        await move(page, CHK_COMPASS_X, CHK_COMPASS_Y, 700)
        await ring(page, CHK_COMPASS_X, CHK_COMPASS_Y)
        await sleep(1.5)
        await move(page, CHK_EARTH_X, CHK_EARTH_Y, 700)
        await ring(page, CHK_EARTH_X, CHK_EARTH_Y)
        await sleep(1.5)
        await move(page, RESET_CX, RESET_CY, 700)
        await ring(page, RESET_CX, RESET_CY)
        await sleep(1.5)
        # Pan over the simulation canvas
        cx, cy = s2p(0, 0)
        await move(page, cx, cy, 900)
        await sleep(2)
        await move(page, *s2p(0.6, 0.5), 900)
        await sleep(2)
        await move(page, *s2p(-0.8, -0.4), 900)
        await sleep(2)
        await hide_cap(page)
        await sleep(max(0.1, SEC_DUR["01_intro"] - (_time.time()-t0)))

        # ================================================================
        # 02 FIELD VECTORS  (33.2 s)
        # ================================================================
        t0 = _time.time()
        await caption(page, "Field vectors emerge from the N pole and converge at the S pole")
        # Highlight the N-pole region
        px_n, py_n = s2p(0.3, 0.0)
        await move(page, px_n, py_n, 800)
        await ring(page, px_n, py_n)
        await sleep(2)
        # Trace an arc from N pole over top to S pole
        for sx in [0.5, 0.3, 0.0, -0.3, -0.5]:
            sy = 0.55 - abs(sx) * 0.1   # approximate arc
            await move(page, *s2p(sx, sy), 600)
            await sleep(0.5)
        await sleep(1)
        px_s, py_s = s2p(-0.3, 0.0)
        await move(page, px_s, py_s, 700)
        await ring(page, px_s, py_s)
        await sleep(2)
        await caption(page, "Field strength B falls as 1/r³ — arrows are longest near the poles")
        # Highlight close vs far
        await move(page, *s2p(0.25, 0.0), 700)
        await ring(page, *s2p(0.25, 0.0))
        await sleep(1.5)
        await move(page, *s2p(1.1, 0.0), 900)
        await ring(page, *s2p(1.1, 0.0))
        await sleep(2)
        await hide_cap(page)
        await sleep(max(0.1, SEC_DUR["02_field_vectors"] - (_time.time()-t0)))

        # ================================================================
        # 03 ROTATE VIA PRESET DROPDOWN  (36.6 s)
        # ================================================================
        t0 = _time.time()
        await caption(page, "Use the dropdown to rotate the magnet to preset orientations")
        await sleep(1.5)
        presets = [
            ("magnet points right", "Magnet RIGHT — N pole to the right, S pole to the left"),
            ("magnet points up",    "Magnet UP — entire field pattern rotates 90°"),
            ("magnet points left",  "Magnet LEFT — poles swap, arrows reverse direction"),
            ("magnet points down",  "Magnet DOWN — field rotates −90° from default"),
            ("magnet points right", "Back to the default orientation"),
        ]
        for opt, cap_text in presets:
            await select_magnet_preset(page, opt)
            await caption(page, cap_text, 4800)
            await sleep(5.5)
        await hide_cap(page)
        await sleep(max(0.1, SEC_DUR["03_rotate_magnet_presets"] - (_time.time()-t0)))

        # ================================================================
        # 04 DRAG & PRECISE ROTATION  (41.4 s)
        # ================================================================
        t0 = _time.time()
        await caption(page, "The magnet can be dragged to any position on the canvas")
        await sleep(1.5)
        # Move magnet to several positions; cursor follows
        moves = [
            (0.6,  0.4,  "Magnet offset to upper-right — field pattern shifts with it"),
            (-0.5, -0.3, "Magnet to lower-left — field re-centred around new position"),
            (0.0,  0.0,  "Back to centre"),
        ]
        for sx, sy, cap_text in moves:
            await magnet_to(page, sx, sy)
            px, py = s2p(sx, sy)
            await move(page, px, py, 700)
            await ring(page, px, py)
            await caption(page, cap_text, 4500)
            await sleep(5)
        await caption(page, "Use the angle dropdown (θ₁) to rotate in precise 10° steps")
        await sleep(1.5)
        for deg in [30, 60, 90, 120, 150, 180, 0]:
            await set_angle(page, deg)
            await move(page, *s2p(0.2*math.cos(math.radians(deg)),
                                   0.2*math.sin(math.radians(deg))), 300)
            await sleep(1.5)
        await caption(page, "The field pattern rotates smoothly — dipole symmetry always preserved")
        await sleep(4)
        await hide_cap(page)
        await sleep(max(0.1, SEC_DUR["04_drag_and_rotate"] - (_time.time()-t0)))

        # ================================================================
        # 05 COMPASS PROBE  (46.0 s)
        # ================================================================
        t0 = _time.time()
        await set_angle(page, 0)   # reset to pointing right
        await magnet_to(page, 0.0, 0.0)
        await toggle_compass(page, True)
        await caption(page, "Compass enabled — shows field direction and Bₓ, Bᵧ, |B|, θ readout")
        await sleep(3)
        probes = [
            (0.55,  0.0, "Axial position (right of N pole) — compass aligns with strong axial field"),
            (0.0,   0.7, "Equatorial above centre — compass points opposite to magnet direction"),
            (-0.55, 0.0, "Left of S pole — compass reverses, pointing into the south pole"),
            (0.0,  -0.7, "Below centre — symmetric to the equatorial position above"),
            (1.1,   0.0, "Far along the axis — field weaker, same direction"),
            (0.4,   0.4, "Off-axis — compass tilted by the combined Bx and By components"),
        ]
        for sx, sy, cap_text in probes:
            await compass_to(page, sx, sy)
            px, py = s2p(sx, sy)
            await move(page, px, py, 700)
            await ring(page, px, py)
            await caption(page, cap_text, 5000)
            await sleep(5.5)
        await hide_cap(page)
        await sleep(max(0.1, SEC_DUR["05_compass_probe"] - (_time.time()-t0)))

        # ================================================================
        # 06 COMPASS OSCILLATION  (44.2 s)
        # ================================================================
        t0 = _time.time()
        await compass_to(page, 0.5, 0.4)
        await caption(page, "Click Play — the compass is a damped harmonic oscillator")
        await sleep(2)
        await sim_play(page)
        await sleep(5)
        await caption(page, "It overshoots equilibrium, swings back, then settles — just like a real compass")
        await sleep(5)
        await sim_pause(page)
        await sleep(1)
        # Move to weaker field region
        await compass_to(page, 1.1, 0.6)
        px2, py2 = s2p(1.1, 0.6)
        await move(page, px2, py2, 700)
        await caption(page, "Weaker field region — slower oscillation (smaller restoring torque)")
        await sim_play(page)
        await sleep(5)
        await caption(page, "dω/dt = −k|B|·sin(δθ) − bω  — less |B| means lower frequency")
        await sleep(5)
        await sim_pause(page)
        await sleep(1)
        # Back to strong field
        await compass_to(page, 0.25, 0.0)
        await caption(page, "Back near the pole — rapid oscillation, strong restoring torque")
        await sim_play(page)
        await sleep(5)
        await sim_pause(page)
        await hide_cap(page)
        await sleep(max(0.1, SEC_DUR["06_oscillation"] - (_time.time()-t0)))

        # ================================================================
        # 07 EARTH FIELD  (43.2 s)
        # ================================================================
        t0 = _time.time()
        await toggle_compass(page, True)
        await toggle_earth(page, True)
        await click_pos(page, CHK_EARTH_X, CHK_EARTH_Y, 600)
        await caption(page, "Earth field ON — compass responds to bar magnet + Earth's geomagnetic field")
        await sleep(4)
        # Move compass far from magnet
        await compass_to(page, -1.1, 0.7)
        await move(page, *s2p(-1.1, 0.7), 800)
        await ring(page, *s2p(-1.1, 0.7))
        await caption(page, "Far from the magnet — Earth's field dominates, compass points north")
        await sleep(5)
        # Near north pole
        await compass_to(page, 0.4, 0.0)
        await move(page, *s2p(0.4, 0.0), 800)
        await ring(page, *s2p(0.4, 0.0))
        await caption(page, "Near the N pole — bar magnet dominates, compass pulled away from north")
        await sleep(5)
        # Find neutral point (where fields partially cancel)
        await compass_to(page, -0.4, 0.0)
        await move(page, *s2p(-0.4, 0.0), 800)
        await caption(page, "Between the poles and Earth field — find where they cancel (neutral point)")
        await sleep(5)
        # Demonstrate the interplay by moving the magnet
        await caption(page, "Rotate the magnet — Earth's field stays fixed, bar magnet field rotates")
        for deg in [45, 90, 135, 180, 90, 0]:
            await set_angle(page, deg)
            await sleep(2)
        await hide_cap(page)
        await toggle_earth(page, False)  # turn off for next section
        await sleep(max(0.1, SEC_DUR["07_earth_field"] - (_time.time()-t0)))

        # ================================================================
        # 08 SECOND MAGNET  (44.6 s)
        # ================================================================
        t0 = _time.time()
        await set_angle(page, 0)
        await magnet_to(page, -0.5, 0.0)
        await sim_set(page, {"magnet2": True, "xMagnet2": 0.5, "yMagnet2": 0.0})
        await caption(page, "Second magnet enabled — two dipole fields superimposed")
        await sleep(3)
        px_m1, py_m1 = s2p(-0.5, 0.0)
        px_m2, py_m2 = s2p( 0.5, 0.0)
        await move(page, px_m1, py_m1, 700)
        await ring(page, px_m1, py_m1)
        await sleep(1)
        await move(page, px_m2, py_m2, 700)
        await ring(page, px_m2, py_m2)
        await caption(page, "N poles facing each other — field lines deflected away between them (repulsion)")
        await sleep(5)
        # Flip magnet 1 so S faces N of magnet 2
        await set_angle(page, 180)
        await caption(page, "Opposite poles facing — field lines connect between the magnets (attraction)")
        await sleep(5)
        # Bring them closer
        await magnet_to(page, -0.2, 0.0)
        await sim_set(page, {"xMagnet2": 0.2, "yMagnet2": 0.0})
        await caption(page, "Magnets closer — strong combined field in the gap")
        await sleep(4)
        # Perpendicular arrangement
        await magnet_to(page, 0.0, 0.4)
        await sim_set(page, {"xMagnet2": 0.0, "yMagnet2": -0.4})
        await set_angle(page, 90)
        await caption(page, "Perpendicular arrangement — complex field with neutral points and saddles")
        await sleep(5)
        # Side by side
        await magnet_to(page, -0.6, 0.0)
        await sim_set(page, {"xMagnet2": 0.6, "yMagnet2": 0.0})
        await set_angle(page, 0)
        await caption(page, "Side by side, same orientation — parallel dipole field")
        await sleep(5)
        await hide_cap(page)
        # Hide 2nd magnet for clean conclusion
        await sim_set(page, {"magnet2": False})
        await sleep(max(0.1, SEC_DUR["08_second_magnet"] - (_time.time()-t0)))

        # ================================================================
        # 09 CONCLUSION  (34.3 s)
        # ================================================================
        t0 = _time.time()
        await sim_reset(page)
        await move(page, RESET_CX, RESET_CY, 600)
        await ring(page, RESET_CX, RESET_CY)
        await sleep(1)
        await caption(page, "Reset returns to the default state — start a fresh exploration")
        await sleep(3)
        # Pan over the information panel (right side)
        await move(page, W - 200, H//3, 900)
        await sleep(2)
        await move(page, W - 200, H//2, 600)
        await caption(page, "The information panel has guided activities, physics equations, and controls summary")
        await sleep(4)
        await move(page, W//2, H//2, 800)
        await sleep(2)
        await caption(page,
            "Bar Magnet & Compass Simulation — @lookang  |  iwant2study.org", 8000)
        # Final graceful pan
        await move(page, *s2p(0.5, 0.5), 1000)
        await sleep(2)
        await move(page, *s2p(-0.5, -0.5), 1200)
        await sleep(2)
        await move(page, *s2p(0, 0), 800)
        await sleep(4)
        await hide_cap(page)
        await sleep(max(0.1, SEC_DUR["09_conclusion"] - (_time.time()-t0)))

        # ----------------------------------------------------------------
        video_path = await page.video.path()
        await ctx.close()
        await browser.close()

    print(f"\nRaw video: {video_path}")
    return Path(video_path)


def mux(webm: Path):
    import subprocess
    if not NARR_MP3.exists():
        print("WARNING: narration_magnetic.mp3 not found - saving video-only")
        cmd = ["ffmpeg","-y","-i",str(webm),"-c:v","libx264","-preset","fast",
               "-crf","22","-pix_fmt","yuv420p",str(OUT_MP4)]
    else:
        cmd = ["ffmpeg","-y",
               "-i",str(webm), "-i",str(NARR_MP3),
               "-c:v","libx264","-preset","fast","-crf","22","-pix_fmt","yuv420p",
               "-c:a","aac","-b:a","192k","-shortest",
               str(OUT_MP4)]
    print("Muxing ...")
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode == 0:
        size = OUT_MP4.stat().st_size / (1024*1024)
        print(f"Done: {OUT_MP4}  ({size:.1f} MB)")
    else:
        print("ffmpeg error:\n", r.stderr[-2000:])


if __name__ == "__main__":
    webm = asyncio.run(record_video())
    mux(webm)
